/*
THIS IS A GENERATED/BUNDLED FILE BY ESBUILD
if you want to view the source, please visit the github repository of this plugin
*/

var __defProp = Object.defineProperty;
var __getOwnPropDesc = Object.getOwnPropertyDescriptor;
var __getOwnPropNames = Object.getOwnPropertyNames;
var __hasOwnProp = Object.prototype.hasOwnProperty;
var __export = (target, all) => {
  for (var name in all)
    __defProp(target, name, { get: all[name], enumerable: true });
};
var __copyProps = (to, from, except, desc) => {
  if (from && typeof from === "object" || typeof from === "function") {
    for (let key of __getOwnPropNames(from))
      if (!__hasOwnProp.call(to, key) && key !== except)
        __defProp(to, key, { get: () => from[key], enumerable: !(desc = __getOwnPropDesc(from, key)) || desc.enumerable });
  }
  return to;
};
var __toCommonJS = (mod) => __copyProps(__defProp({}, "__esModule", { value: true }), mod);

// main.ts
var main_exports = {};
__export(main_exports, {
  default: () => AIMetadataPlugin
});
module.exports = __toCommonJS(main_exports);
var import_obsidian7 = require("obsidian");

// src/ai-provider.ts
var import_obsidian = require("obsidian");
var PLATFORM_DEFAULTS = {
  claude: {
    name: "Claude (Anthropic)",
    baseUrl: "https://api.anthropic.com",
    models: ["claude-sonnet-4-6", "claude-opus-4-6", "claude-haiku-4-5"],
    defaultModel: "claude-sonnet-4-6"
  },
  openai: {
    name: "OpenAI",
    baseUrl: "https://api.openai.com/v1",
    models: ["gpt-4o", "gpt-4o-mini", "gpt-4-turbo", "gpt-3.5-turbo"],
    defaultModel: "gpt-4o"
  },
  deepseek: {
    name: "DeepSeek",
    baseUrl: "https://api.deepseek.com",
    models: ["deepseek-chat", "deepseek-coder"],
    defaultModel: "deepseek-chat"
  },
  qwen: {
    name: "\u901A\u4E49\u5343\u95EE (Aliyun)",
    baseUrl: "https://dashscope.aliyuncs.com/compatible-mode/v1",
    models: ["qwen-turbo", "qwen-plus", "qwen-max", "qwen-coder-plus"],
    defaultModel: "qwen-plus"
  },
  zhipu: {
    name: "\u667A\u8C31 AI (GLM)",
    baseUrl: "https://open.bigmodel.cn/api/paas/v4",
    models: ["glm-4", "glm-4-flash", "glm-4-air", "glm-4-long"],
    defaultModel: "glm-4"
  },
  spark: {
    name: "\u8BAF\u98DE\u661F\u706B",
    baseUrl: "https://spark-api-open.xf-yun.com/v1",
    models: ["lite", "pro", "pro-128k", "max", "4.0-ultra"],
    defaultModel: "pro"
  },
  ollama: {
    name: "Ollama (\u672C\u5730)",
    baseUrl: "http://localhost:11434/v1",
    models: ["llama3.2", "llama3.1", "llama3", "mistral", "mixtral", "gemma3", "qwen2.5", "deepseek-r1", "phi4", "codellama"],
    defaultModel: "llama3.2"
  },
  lmstudio: {
    name: "LM Studio (\u672C\u5730)",
    baseUrl: "http://localhost:1234/v1",
    models: [],
    defaultModel: ""
  }
};
function buildSystemPrompt(existingTags, existingCategories) {
  let prompt = `\u4F60\u662F\u4E00\u4E2A\u4E13\u4E1A\u7684\u5185\u5BB9\u5206\u6790\u52A9\u624B\u3002\u8BF7\u5206\u6790\u7528\u6237\u63D0\u4F9B\u7684\u6587\u7AE0\u5185\u5BB9\uFF0C\u5E76\u751F\u6210\u4EE5\u4E0B\u5143\u6570\u636E\uFF1A

1. **title**: \u4E00\u4E2A\u7B80\u6D01\u3001\u51C6\u786E\u7684\u6807\u9898\uFF08\u4E0D\u8D85\u8FC750\u4E2A\u5B57\u7B26\uFF09
2. **tags**: 3-8\u4E2A\u76F8\u5173\u6807\u7B7E\uFF0C\u7528\u4E8E\u5185\u5BB9\u5206\u7C7B\u548C\u68C0\u7D22
3. **category**: \u4E00\u4E2A\u4E3B\u8981\u5206\u7C7B\uFF0C\u7528\u4E8E\u7EC4\u7EC7\u5185\u5BB9
4. **summary**: \u4E00\u6BB5\u7B80\u77ED\u7684\u6458\u8981\uFF08100-200\u5B57\uFF09\uFF0C\u6982\u62EC\u6587\u7AE0\u6838\u5FC3\u5185\u5BB9
5. **keywords**: 5-10\u4E2A\u5173\u952E\u8BCD\uFF0C\u7528\u4E8ESEO\u548C\u641C\u7D22\u4F18\u5316\uFF08\u4E0D\u540C\u4E8Etags\uFF0Ckeywords\u66F4\u4FA7\u91CD\u5185\u5BB9\u6838\u5FC3\u6982\u5FF5\uFF09

\u8BF7\u4EE5 JSON \u683C\u5F0F\u8FD4\u56DE\u7ED3\u679C\uFF0C\u683C\u5F0F\u5982\u4E0B\uFF1A
{
  "title": "\u751F\u6210\u7684\u6807\u9898",
  "tags": ["\u6807\u7B7E1", "\u6807\u7B7E2", "\u6807\u7B7E3"],
  "category": "\u5206\u7C7B\u540D\u79F0",
  "summary": "\u6587\u7AE0\u6458\u8981...",
  "keywords": ["\u5173\u952E\u8BCD1", "\u5173\u952E\u8BCD2", "\u5173\u952E\u8BCD3"]
}

\u8981\u6C42\uFF1A
- \u6807\u7B7E\u4F7F\u7528\u4E2D\u6587\u6216\u82F1\u6587\uFF0C\u4FDD\u6301\u7B80\u6D01
- \u907F\u514D\u8FC7\u4E8E\u5BBD\u6CDB\u7684\u6807\u7B7E\uFF08\u5982"\u7B14\u8BB0"\u3001"\u6587\u6863"\uFF09
- \u6458\u8981\u8981\u51C6\u786E\u53CD\u6620\u6587\u7AE0\u7684\u6838\u5FC3\u89C2\u70B9
- keywords \u5E94\u8BE5\u662F\u6587\u7AE0\u7684\u6838\u5FC3\u6982\u5FF5\u3001\u6280\u672F\u672F\u8BED\u3001\u5173\u952E\u5B9E\u4F53\u7B49\uFF0C\u7528\u4E8E\u641C\u7D22\u53D1\u73B0`;
  if (existingTags.length > 0) {
    prompt += `

**\u91CD\u8981\uFF1A\u4F18\u5148\u4F7F\u7528\u4EE5\u4E0B\u5DF2\u6709\u6807\u7B7E**\uFF08\u5982\u679C\u5185\u5BB9\u76F8\u5173\uFF09\uFF1A
${existingTags.join(", ")}`;
  }
  if (existingCategories.length > 0) {
    prompt += `

**\u91CD\u8981\uFF1A\u4F18\u5148\u4ECE\u4EE5\u4E0B\u5DF2\u6709\u5206\u7C7B\u4E2D\u9009\u62E9**\uFF08\u5982\u679C\u5185\u5BB9\u5339\u914D\uFF09\uFF1A
${existingCategories.join(", ")}`;
  }
  prompt += `

\u8BF7\u53EA\u8FD4\u56DE JSON \u683C\u5F0F\u7684\u7ED3\u679C\uFF0C\u4E0D\u8981\u5305\u542B\u5176\u4ED6\u8BF4\u660E\u6587\u5B57\u3002`;
  return prompt;
}
function parseResponse(response) {
  try {
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      return {
        title: parsed.title || "\u672A\u547D\u540D",
        tags: Array.isArray(parsed.tags) ? parsed.tags : [],
        category: parsed.category || "\u672A\u5206\u7C7B",
        summary: parsed.summary || "",
        keywords: Array.isArray(parsed.keywords) ? parsed.keywords : []
      };
    }
    throw new Error("\u65E0\u6CD5\u89E3\u6790 AI \u54CD\u5E94");
  } catch (error) {
    console.error("\u89E3\u6790 AI \u54CD\u5E94\u5931\u8D25:", error);
    return {
      title: "\u89E3\u6790\u5931\u8D25",
      tags: [],
      category: "\u672A\u5206\u7C7B",
      summary: "",
      keywords: []
    };
  }
}
function parseOptimizationResponse(response) {
  try {
    const textMatch = response.match(/===优化后的文本===\s*\n?([\s\S]*?)(?:\n?===优化说明===|$)/);
    const explanationMatch = response.match(/===优化说明===\s*\n?([\s\S]*?)$/);
    if (textMatch) {
      return {
        optimizedText: textMatch[1].trim(),
        explanation: explanationMatch ? explanationMatch[1].trim() : ""
      };
    }
    const jsonMatch = response.match(/\{[\s\S]*\}/);
    if (jsonMatch) {
      const parsed = JSON.parse(jsonMatch[0]);
      return {
        optimizedText: parsed.optimizedText || parsed.text || response,
        explanation: parsed.explanation || parsed.changes || ""
      };
    }
    return {
      optimizedText: response.trim(),
      explanation: ""
    };
  } catch (e) {
    return {
      optimizedText: response.trim(),
      explanation: ""
    };
  }
}
function buildOptimizePrompt(isPartial) {
  if (isPartial) {
    return `\u4F60\u662F\u4E00\u4F4D\u4E13\u4E1A\u7684\u5199\u4F5C\u7F16\u8F91\u3002\u8BF7\u4F18\u5316\u7528\u6237\u63D0\u4F9B\u7684\u6587\u672C\u7247\u6BB5\uFF0C\u6539\u8FDB\u5176\u8868\u8FBE\u548C\u53D9\u8FF0\u7ED3\u6784\u3002

\u8981\u6C42\uFF1A
1. \u4FDD\u6301\u539F\u6587\u7684\u6838\u5FC3\u610F\u601D\u4E0D\u53D8
2. \u6539\u8FDB\u8BED\u8A00\u8868\u8FBE\uFF0C\u4F7F\u5176\u66F4\u52A0\u6D41\u7545\u3001\u51C6\u786E
3. \u4F18\u5316\u53E5\u5B50\u7ED3\u6784\uFF0C\u589E\u5F3A\u53EF\u8BFB\u6027
4. \u4FEE\u6B63\u8BED\u6CD5\u9519\u8BEF\u548C\u4E0D\u6070\u5F53\u7684\u7528\u8BCD
5. \u4FDD\u6301\u6587\u672C\u7247\u6BB5\u7684\u539F\u6709\u98CE\u683C

\u8BF7\u6309\u4EE5\u4E0B\u683C\u5F0F\u8FD4\u56DE\u7ED3\u679C\uFF1A

===\u4F18\u5316\u540E\u7684\u6587\u672C===
\uFF08\u5728\u8FD9\u91CC\u8F93\u51FA\u4F18\u5316\u540E\u7684\u6587\u672C\u5185\u5BB9\uFF0C\u4FDD\u6301Markdown\u683C\u5F0F\uFF0C\u4E0D\u8981\u5305\u542BJSON\u683C\u5F0F\u6216\u4EE3\u7801\u5757\uFF09

===\u4F18\u5316\u8BF4\u660E===
1. \u6539\u8FDB\u70B9\u4E00\u7684\u8BF4\u660E
2. \u6539\u8FDB\u70B9\u4E8C\u7684\u8BF4\u660E
3. \u6539\u8FDB\u70B9\u4E09\u7684\u8BF4\u660E
\uFF08\u6309\u6761\u76EE\u5217\u51FA\u4E3B\u8981\u6539\u8FDB\u70B9\uFF0C\u7EAF\u6587\u672C\u683C\u5F0F\uFF0C\u4E0D\u8981\u4F7F\u7528Markdown\u52A0\u7C97\u3001\u659C\u4F53\u7B49\u683C\u5F0F\uFF09`;
  } else {
    return `\u4F60\u662F\u4E00\u4F4D\u4E13\u4E1A\u7684\u5199\u4F5C\u7F16\u8F91\u3002\u8BF7\u4F18\u5316\u7528\u6237\u63D0\u4F9B\u7684\u6587\u7AE0\uFF0C\u6539\u8FDB\u5176\u6574\u4F53\u8868\u8FBE\u548C\u53D9\u8FF0\u7ED3\u6784\u3002

\u8981\u6C42\uFF1A
1. \u4FDD\u6301\u539F\u6587\u7684\u6838\u5FC3\u610F\u601D\u548C\u4E3B\u9898\u4E0D\u53D8
2. \u6539\u8FDB\u8BED\u8A00\u8868\u8FBE\uFF0C\u4F7F\u5176\u66F4\u52A0\u6D41\u7545\u3001\u51C6\u786E\u3001\u4E13\u4E1A
3. \u4F18\u5316\u6587\u7AE0\u7ED3\u6784\uFF0C\u589E\u5F3A\u903B\u8F91\u6027\u548C\u53EF\u8BFB\u6027
4. \u4FEE\u6B63\u8BED\u6CD5\u9519\u8BEF\u3001\u9519\u522B\u5B57\u548C\u4E0D\u6070\u5F53\u7684\u7528\u8BCD
5. \u4FDD\u6301\u6587\u7AE0\u7684\u539F\u6709\u98CE\u683C\u548C\u8BED\u6C14
6. \u53EF\u4EE5\u9002\u5F53\u8C03\u6574\u6BB5\u843D\u7ED3\u6784\uFF0C\u4F7F\u6587\u7AE0\u66F4\u6709\u5C42\u6B21\u611F

\u8BF7\u6309\u4EE5\u4E0B\u683C\u5F0F\u8FD4\u56DE\u7ED3\u679C\uFF1A

===\u4F18\u5316\u540E\u7684\u6587\u672C===
\uFF08\u5728\u8FD9\u91CC\u8F93\u51FA\u4F18\u5316\u540E\u7684\u6587\u672C\u5185\u5BB9\uFF0C\u4FDD\u6301Markdown\u683C\u5F0F\uFF0C\u4E0D\u8981\u5305\u542BJSON\u683C\u5F0F\u6216\u4EE3\u7801\u5757\uFF09

===\u4F18\u5316\u8BF4\u660E===
1. \u6539\u8FDB\u70B9\u4E00\u7684\u8BF4\u660E
2. \u6539\u8FDB\u70B9\u4E8C\u7684\u8BF4\u660E
3. \u6539\u8FDB\u70B9\u4E09\u7684\u8BF4\u660E
\uFF08\u6309\u6761\u76EE\u5217\u51FA\u4E3B\u8981\u6539\u8FDB\u70B9\uFF0C\u5982\u7ED3\u6784\u8C03\u6574\u3001\u8BED\u8A00\u6DA6\u8272\u7B49\uFF0C\u7EAF\u6587\u672C\u683C\u5F0F\uFF0C\u4E0D\u8981\u4F7F\u7528Markdown\u52A0\u7C97\u3001\u659C\u4F53\u7B49\u683C\u5F0F\uFF09`;
  }
}
var ClaudeProvider = class {
  constructor(config) {
    this.config = config;
  }
  async analyze(content, existingTags = [], existingCategories = []) {
    const systemPrompt = buildSystemPrompt(existingTags, existingCategories);
    const response = await (0, import_obsidian.requestUrl)({
      url: `${this.config.baseUrl || PLATFORM_DEFAULTS.claude.baseUrl}/v1/messages`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.config.apiKey,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: this.config.model,
        max_tokens: this.config.maxTokens || 4096,
        system: systemPrompt,
        messages: [
          {
            role: "user",
            content: `\u8BF7\u5206\u6790\u4EE5\u4E0B\u6587\u7AE0\u5185\u5BB9\uFF0C\u751F\u6210\u5408\u9002\u7684\u5143\u6570\u636E\uFF1A

${content}`
          }
        ]
      })
    });
    if (response.status !== 200) {
      throw new Error(`Claude API \u8BF7\u6C42\u5931\u8D25: ${response.status} ${response.text}`);
    }
    const data = response.json;
    const textContent = data.content.filter((block) => block.type === "text").map((block) => block.text).join("");
    return parseResponse(textContent);
  }
  async optimize(content, isPartial = false) {
    const systemPrompt = buildOptimizePrompt(isPartial);
    const response = await (0, import_obsidian.requestUrl)({
      url: `${this.config.baseUrl || PLATFORM_DEFAULTS.claude.baseUrl}/v1/messages`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "x-api-key": this.config.apiKey,
        "anthropic-version": "2023-06-01"
      },
      body: JSON.stringify({
        model: this.config.model,
        max_tokens: this.config.maxTokens || 4096,
        system: systemPrompt,
        messages: [
          {
            role: "user",
            content
          }
        ]
      })
    });
    if (response.status !== 200) {
      throw new Error(`Claude API \u8BF7\u6C42\u5931\u8D25: ${response.status} ${response.text}`);
    }
    const data = response.json;
    const textContent = data.content.filter((block) => block.type === "text").map((block) => block.text).join("");
    return parseOptimizationResponse(textContent);
  }
};
var OpenAICompatibleProvider = class {
  constructor(platform, config) {
    this.platform = platform;
    this.config = config;
  }
  async analyze(content, existingTags = [], existingCategories = []) {
    var _a, _b, _c, _d;
    const systemPrompt = buildSystemPrompt(existingTags, existingCategories);
    const baseUrl = this.config.baseUrl || PLATFORM_DEFAULTS[this.platform].baseUrl;
    const response = await (0, import_obsidian.requestUrl)({
      url: `${baseUrl}/chat/completions`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.config.apiKey}`
      },
      body: JSON.stringify({
        model: this.config.model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content: `\u8BF7\u5206\u6790\u4EE5\u4E0B\u6587\u7AE0\u5185\u5BB9\uFF0C\u751F\u6210\u5408\u9002\u7684\u5143\u6570\u636E\uFF1A

${content}` }
        ],
        max_tokens: this.config.maxTokens || 4096,
        temperature: (_a = this.config.temperature) != null ? _a : 0.7
      })
    });
    if (response.status !== 200) {
      throw new Error(`${PLATFORM_DEFAULTS[this.platform].name} API \u8BF7\u6C42\u5931\u8D25: ${response.status} ${response.text}`);
    }
    const data = response.json;
    const textContent = ((_d = (_c = (_b = data.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.message) == null ? void 0 : _d.content) || "";
    return parseResponse(textContent);
  }
  async optimize(content, isPartial = false) {
    var _a, _b, _c, _d;
    const systemPrompt = buildOptimizePrompt(isPartial);
    const baseUrl = this.config.baseUrl || PLATFORM_DEFAULTS[this.platform].baseUrl;
    const response = await (0, import_obsidian.requestUrl)({
      url: `${baseUrl}/chat/completions`,
      method: "POST",
      headers: {
        "Content-Type": "application/json",
        "Authorization": `Bearer ${this.config.apiKey}`
      },
      body: JSON.stringify({
        model: this.config.model,
        messages: [
          { role: "system", content: systemPrompt },
          { role: "user", content }
        ],
        max_tokens: this.config.maxTokens || 4096,
        temperature: (_a = this.config.temperature) != null ? _a : 0.7
      })
    });
    if (response.status !== 200) {
      throw new Error(`${PLATFORM_DEFAULTS[this.platform].name} API \u8BF7\u6C42\u5931\u8D25: ${response.status} ${response.text}`);
    }
    const data = response.json;
    const textContent = ((_d = (_c = (_b = data.choices) == null ? void 0 : _b[0]) == null ? void 0 : _c.message) == null ? void 0 : _d.content) || "";
    return parseOptimizationResponse(textContent);
  }
};
async function fetchOllamaModels(baseUrl) {
  try {
    const rootUrl = baseUrl.replace(/\/v1\/?$/, "");
    const response = await (0, import_obsidian.requestUrl)({
      url: `${rootUrl}/api/tags`,
      method: "GET"
    });
    if (response.status === 200) {
      const data = response.json;
      return (data.models || []).map(
        (m) => m.name
      );
    }
    return [];
  } catch (e) {
    return [];
  }
}
async function fetchLMStudioModels(baseUrl) {
  try {
    const response = await (0, import_obsidian.requestUrl)({
      url: `${baseUrl}/models`,
      method: "GET"
    });
    if (response.status === 200) {
      const data = response.json;
      return (data.data || []).map(
        (m) => m.id
      );
    }
    return [];
  } catch (e) {
    return [];
  }
}
function createAIProvider(platform, config) {
  switch (platform) {
    case "claude":
      return new ClaudeProvider(config);
    case "openai":
    case "deepseek":
    case "qwen":
    case "zhipu":
    case "spark":
    case "ollama":
    case "lmstudio":
      return new OpenAICompatibleProvider(platform, config);
    default:
      throw new Error(`\u4E0D\u652F\u6301\u7684 AI \u5E73\u53F0: ${String(platform)}`);
  }
}

// src/vault-scanner.ts
var import_obsidian2 = require("obsidian");
var VaultScanner = class {
  constructor(vault, getAllTags, getFileCache, getCachedFiles) {
    this.vault = vault;
    this.getAllTags = getAllTags;
    this.getFileCache = getFileCache;
    this.getCachedFiles = getCachedFiles;
  }
  /**
   * 获取所有标签（使用 Obsidian MetadataCache API）
   */
  getAllVaultTags() {
    const tags = /* @__PURE__ */ new Map();
    try {
      const allTags = this.getAllTags();
      if (!allTags || typeof allTags !== "object") {
        return tags;
      }
      for (const [tagWithHash, count] of Object.entries(allTags)) {
        const tag = tagWithHash.startsWith("#") ? tagWithHash.slice(1) : tagWithHash;
        tags.set(tag, count);
      }
    } catch (error) {
      console.error("\u83B7\u53D6\u6807\u7B7E\u5931\u8D25:", error);
    }
    return tags;
  }
  /**
   * 从 frontmatter 中获取分类（使用 Obsidian MetadataCache，遍历缓存的文件）
   */
  getCategoriesFromMetadata() {
    var _a;
    const categories = /* @__PURE__ */ new Map();
    try {
      const cachedFiles = this.getCachedFiles();
      for (const filePath of cachedFiles) {
        const file = this.vault.getAbstractFileByPath(filePath);
        if (file instanceof import_obsidian2.TFile) {
          const cache = this.getFileCache(file);
          if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.category) {
            const category = String(cache.frontmatter.category).trim();
            if (category) {
              categories.set(category, (categories.get(category) || 0) + 1);
            }
          }
        }
      }
    } catch (error) {
      console.error("\u83B7\u53D6\u5206\u7C7B\u5931\u8D25:", error);
    }
    return categories;
  }
  /**
   * 从文件夹结构获取分类
   */
  getCategoriesFromFolders() {
    const categories = /* @__PURE__ */ new Map();
    const root = this.vault.getRoot();
    this.collectFolderNames(root, categories);
    return categories;
  }
  collectFolderNames(folder, categories, depth = 0) {
    if (depth > 3)
      return;
    for (const child of folder.children) {
      if (child instanceof import_obsidian2.TFolder) {
        const name = child.name;
        if (name && !name.startsWith(".") && name !== "") {
          categories.set(name, (categories.get(name) || 0) + 1);
        }
        this.collectFolderNames(child, categories, depth + 1);
      }
    }
  }
  /**
   * 获取综合的 Vault 笔记属性
   */
  getVaultMetadata(useFoldersAsCategories = true) {
    const tags = this.getAllVaultTags();
    let categories = this.getCategoriesFromMetadata();
    if (useFoldersAsCategories && categories.size < 10) {
      const folderCategories = this.getCategoriesFromFolders();
      for (const [cat, count] of folderCategories) {
        categories.set(cat, (categories.get(cat) || 0) + count);
      }
    }
    return { tags, categories };
  }
  /**
   * 获取最常用的标签（按使用频率排序）
   */
  getTopTags(tags, limit = 50) {
    return Array.from(tags.entries()).sort((a, b) => b[1] - a[1]).slice(0, limit).map(([tag]) => tag);
  }
  /**
   * 获取最常用的分类（按使用频率排序）
   */
  getTopCategories(categories, limit = 20) {
    return Array.from(categories.entries()).sort((a, b) => b[1] - a[1]).slice(0, limit).map(([category]) => category);
  }
  /**
   * 根据内容推荐相关标签（简单关键词匹配）
   */
  recommendTags(content, existingTags, limit = 10) {
    const contentLower = content.toLowerCase();
    const scores = /* @__PURE__ */ new Map();
    for (const [tag] of existingTags) {
      let score = 0;
      const tagLower = tag.toLowerCase();
      if (contentLower.includes(tagLower)) {
        score += 10;
      }
      const tagParts = tagLower.split("/");
      for (const part of tagParts) {
        if (part.length > 2 && contentLower.includes(part)) {
          score += 3;
        }
      }
      if (score > 0) {
        scores.set(tag, score);
      }
    }
    return Array.from(scores.entries()).sort((a, b) => b[1] - a[1]).slice(0, limit).map(([tag]) => tag);
  }
  /**
   * 根据文件夹结构推断分类
   */
  getFolderCategories(file) {
    const categories = [];
    let current = file.parent;
    while (current && current.path !== "/" && current.path !== "") {
      categories.push(current.name);
      current = current.parent;
    }
    return categories.reverse();
  }
  /**
   * 获取文件已有的标签（来自 frontmatter 和内联标签）
   */
  getFileTags(file) {
    var _a;
    const tags = [];
    try {
      const cache = this.getFileCache(file);
      if (cache) {
        if ((_a = cache.frontmatter) == null ? void 0 : _a.tags) {
          const fmTags = cache.frontmatter.tags;
          if (Array.isArray(fmTags)) {
            tags.push(...fmTags.map((t) => String(t)));
          } else if (typeof fmTags === "string") {
            tags.push(...fmTags.split(/[,\s]+/));
          }
        }
        if (cache.tags) {
          for (const tagInfo of cache.tags) {
            const tag = tagInfo.tag.startsWith("#") ? tagInfo.tag.slice(1) : tagInfo.tag;
            tags.push(tag);
          }
        }
      }
    } catch (error) {
      console.error("\u83B7\u53D6\u6587\u4EF6\u6807\u7B7E\u5931\u8D25:", error);
    }
    return [...new Set(tags.filter((t) => t.length > 0))];
  }
  /**
   * 获取文件的分类（来自 frontmatter）
   */
  getFileCategory(file) {
    var _a;
    try {
      const cache = this.getFileCache(file);
      if ((_a = cache == null ? void 0 : cache.frontmatter) == null ? void 0 : _a.category) {
        return String(cache.frontmatter.category).trim();
      }
    } catch (error) {
      console.error("\u83B7\u53D6\u6587\u4EF6\u5206\u7C7B\u5931\u8D25:", error);
    }
    return null;
  }
};

// src/settings.ts
var DEFAULT_PLATFORM_CONFIG = {
  apiKey: "",
  model: "",
  baseUrl: "",
  temperature: 0.7,
  maxTokens: 4096
};
var DEFAULT_SETTINGS = {
  activePlatform: "claude",
  platforms: {
    claude: {
      ...DEFAULT_PLATFORM_CONFIG,
      model: PLATFORM_DEFAULTS.claude.defaultModel,
      baseUrl: PLATFORM_DEFAULTS.claude.baseUrl
    },
    openai: {
      ...DEFAULT_PLATFORM_CONFIG,
      model: PLATFORM_DEFAULTS.openai.defaultModel,
      baseUrl: PLATFORM_DEFAULTS.openai.baseUrl
    },
    deepseek: {
      ...DEFAULT_PLATFORM_CONFIG,
      model: PLATFORM_DEFAULTS.deepseek.defaultModel,
      baseUrl: PLATFORM_DEFAULTS.deepseek.baseUrl
    },
    qwen: {
      ...DEFAULT_PLATFORM_CONFIG,
      model: PLATFORM_DEFAULTS.qwen.defaultModel,
      baseUrl: PLATFORM_DEFAULTS.qwen.baseUrl
    },
    zhipu: {
      ...DEFAULT_PLATFORM_CONFIG,
      model: PLATFORM_DEFAULTS.zhipu.defaultModel,
      baseUrl: PLATFORM_DEFAULTS.zhipu.baseUrl
    },
    spark: {
      ...DEFAULT_PLATFORM_CONFIG,
      model: PLATFORM_DEFAULTS.spark.defaultModel,
      baseUrl: PLATFORM_DEFAULTS.spark.baseUrl
    },
    ollama: {
      ...DEFAULT_PLATFORM_CONFIG,
      model: PLATFORM_DEFAULTS.ollama.defaultModel,
      baseUrl: PLATFORM_DEFAULTS.ollama.baseUrl
    },
    lmstudio: {
      ...DEFAULT_PLATFORM_CONFIG,
      model: PLATFORM_DEFAULTS.lmstudio.defaultModel,
      baseUrl: PLATFORM_DEFAULTS.lmstudio.baseUrl
    }
  },
  maxTags: 5,
  includeFolderStructure: true,
  customPrompt: "",
  showRibbonIcon: false,
  showEditorMenu: true,
  showOptimizeMenu: true,
  showOptimizePreview: true,
  showPreview: true
};

// src/ui/setting-tab.ts
var import_obsidian3 = require("obsidian");
var LOCAL_PLATFORMS = ["ollama", "lmstudio"];
function isLocalPlatform(p) {
  return LOCAL_PLATFORMS.includes(p);
}
function getFetchFunction(platform) {
  switch (platform) {
    case "ollama":
      return fetchOllamaModels;
    case "lmstudio":
      return fetchLMStudioModels;
  }
}
var AIMetadataSettingTab = class extends import_obsidian3.PluginSettingTab {
  constructor(app, plugin) {
    super(app, plugin);
    this.activeTab = "model";
    this.plugin = plugin;
  }
  display() {
    const { containerEl } = this;
    containerEl.empty();
    const tabBar = containerEl.createEl("nav", { cls: "ai-settings-tab-bar" });
    const modelTab = tabBar.createEl("div", {
      cls: "ai-settings-tab" + (this.activeTab === "model" ? " ai-settings-tab-active" : " ai-settings-tab-inactive")
    });
    const modelIcon = modelTab.createEl("div", { cls: "ai-settings-tab-icon" });
    const modelSvg = modelIcon.createSvg("svg", {
      attr: {
        xmlns: "http://www.w3.org/2000/svg",
        width: "18",
        height: "18",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }
    });
    modelSvg.createSvg("path", { attr: { d: "M12 2L2 7l10 5 10-5-10-5zM2 17l10 5 10-5M2 12l10 5 10-5" } });
    modelTab.createEl("div", {
      cls: "ai-settings-tab-name",
      text: "AI \u6A21\u578B\u914D\u7F6E"
    });
    const featureTab = tabBar.createEl("div", {
      cls: "ai-settings-tab" + (this.activeTab === "feature" ? " ai-settings-tab-active" : " ai-settings-tab-inactive")
    });
    const featureIcon = featureTab.createEl("div", { cls: "ai-settings-tab-icon" });
    const featureSvg = featureIcon.createSvg("svg", {
      attr: {
        xmlns: "http://www.w3.org/2000/svg",
        width: "18",
        height: "18",
        viewBox: "0 0 24 24",
        fill: "none",
        stroke: "currentColor",
        "stroke-width": "2",
        "stroke-linecap": "round",
        "stroke-linejoin": "round"
      }
    });
    featureSvg.createSvg("circle", { attr: { cx: "12", cy: "12", r: "3" } });
    featureSvg.createSvg("path", { attr: { d: "M19.4 15a1.65 1.65 0 0 0 .33 1.82l.06.06a2 2 0 0 1 0 2.83 2 2 0 0 1-2.83 0l-.06-.06a1.65 1.65 0 0 0-1.82-.33 1.65 1.65 0 0 0-1 1.51V21a2 2 0 0 1-2 2 2 2 0 0 1-2-2v-.09A1.65 1.65 0 0 0 9 19.4a1.65 1.65 0 0 0-1.82.33l-.06.06a2 2 0 0 1-2.83 0 2 2 0 0 1 0-2.83l.06-.06a1.65 1.65 0 0 0 .33-1.82 1.65 1.65 0 0 0-1.51-1H3a2 2 0 0 1-2-2 2 2 0 0 1 2-2h.09A1.65 1.65 0 0 0 4.6 9a1.65 1.65 0 0 0-.33-1.82l-.06-.06a2 2 0 0 1 0-2.83 2 2 0 0 1 2.83 0l.06.06a1.65 1.65 0 0 0 1.82.33H9a1.65 1.65 0 0 0 1-1.51V3a2 2 0 0 1 2-2 2 2 0 0 1 2 2v.09a1.65 1.65 0 0 0 1 1.51 1.65 1.65 0 0 0 1.82-.33l.06-.06a2 2 0 0 1 2.83 0 2 2 0 0 1 0 2.83l-.06.06a1.65 1.65 0 0 0-.33 1.82V9a1.65 1.65 0 0 0 1.51 1H21a2 2 0 0 1 2 2 2 2 0 0 1-2 2h-.09a1.65 1.65 0 0 0-1.51 1z" } });
    featureTab.createEl("div", {
      cls: "ai-settings-tab-name",
      text: "\u63D2\u4EF6\u529F\u80FD\u914D\u7F6E"
    });
    if (this.activeTab === "model") {
      modelTab.classList.add("ai-settings-tab-active");
      modelTab.classList.remove("ai-settings-tab-inactive");
      featureTab.classList.add("ai-settings-tab-inactive");
      featureTab.classList.remove("ai-settings-tab-active");
    } else {
      featureTab.classList.add("ai-settings-tab-active");
      featureTab.classList.remove("ai-settings-tab-inactive");
      modelTab.classList.add("ai-settings-tab-inactive");
      modelTab.classList.remove("ai-settings-tab-active");
    }
    modelTab.addEventListener("mouseenter", () => {
      if (this.activeTab !== "model") {
        modelTab.classList.add("ai-settings-tab-hover");
      }
    });
    modelTab.addEventListener("mouseleave", () => {
      modelTab.classList.remove("ai-settings-tab-hover");
    });
    featureTab.addEventListener("mouseenter", () => {
      if (this.activeTab !== "feature") {
        featureTab.classList.add("ai-settings-tab-hover");
      }
    });
    featureTab.addEventListener("mouseleave", () => {
      featureTab.classList.remove("ai-settings-tab-hover");
    });
    modelTab.addEventListener("click", () => {
      this.activeTab = "model";
      this.display();
    });
    featureTab.addEventListener("click", () => {
      this.activeTab = "feature";
      this.display();
    });
    if (this.activeTab === "model") {
      this.displayModelSettings(containerEl);
    } else {
      this.displayFeatureSettings(containerEl);
    }
  }
  displayModelSettings(containerEl) {
    new import_obsidian3.Setting(containerEl).setName("AI \u5E73\u53F0").setDesc("\u9009\u62E9\u8981\u4F7F\u7528\u7684 AI \u5E73\u53F0").addDropdown((dropdown) => {
      for (const [key, value] of Object.entries(PLATFORM_DEFAULTS)) {
        dropdown.addOption(key, value.name);
      }
      dropdown.setValue(this.plugin.settings.activePlatform).onChange(async (value) => {
        this.plugin.settings.activePlatform = value;
        await this.plugin.saveSettings();
        this.display();
      });
    });
    const currentPlatform = this.plugin.settings.activePlatform;
    const platformConfig = this.plugin.settings.platforms[currentPlatform];
    const platformDefaults = PLATFORM_DEFAULTS[currentPlatform];
    new import_obsidian3.Setting(containerEl).setName(`${platformDefaults.name} \u914D\u7F6E`).setHeading();
    const isLocal = isLocalPlatform(currentPlatform);
    const apiKeyDesc = isLocal ? `${platformDefaults.name} \u4E0D\u9700\u8981 API Key\uFF0C\u586B\u5199\u4EFB\u610F\u5360\u4F4D\u7B26\u5373\u53EF` : `${platformDefaults.name} \u7684 API key`;
    new import_obsidian3.Setting(containerEl).setName("API key").setDesc(apiKeyDesc).addText((text) => {
      text.inputEl.type = "password";
      text.setPlaceholder(isLocal ? `${currentPlatform}\uFF08\u5360\u4F4D\u7B26\uFF09` : "\u8F93\u5165 API key...").setValue(platformConfig.apiKey).onChange(async (value) => {
        this.plugin.settings.platforms[currentPlatform].apiKey = value;
        await this.plugin.saveSettings();
      });
    });
    const modelDesc = isLocalPlatform(currentPlatform) ? "\u9009\u62E9\u4F7F\u7528\u7684\u6A21\u578B" : "\u9009\u62E9\u6216\u8F93\u5165\u6A21\u578B\u540D\u79F0\uFF0C\u652F\u6301\u624B\u52A8\u8F93\u5165\u81EA\u5B9A\u4E49\u6A21\u578B";
    const modelSetting = new import_obsidian3.Setting(containerEl).setName("\u6A21\u578B").setDesc(modelDesc);
    if (isLocalPlatform(currentPlatform)) {
      this.buildLocalModelDropdown(modelSetting, platformConfig, currentPlatform);
    } else {
      const datalistId = `ai-model-list-${currentPlatform}`;
      const datalist = containerEl.createEl("datalist");
      datalist.id = datalistId;
      for (const model of platformDefaults.models) {
        datalist.createEl("option", { value: model });
      }
      modelSetting.addText((text) => {
        text.inputEl.setAttribute("list", datalistId);
        text.inputEl.setAttribute("autocomplete", "off");
        text.setPlaceholder("\u8F93\u5165\u6216\u9009\u62E9\u6A21\u578B...").setValue(platformConfig.model || platformDefaults.defaultModel).onChange(async (value) => {
          this.plugin.settings.platforms[currentPlatform].model = value;
          await this.plugin.saveSettings();
        });
      });
    }
    new import_obsidian3.Setting(containerEl).setName("Base URL").setDesc("\u53EF\u9009\uFF0C\u7528\u4E8E\u81EA\u5B9A\u4E49 API \u7AEF\u70B9\u6216\u4EE3\u7406").addText((text) => {
      text.setPlaceholder(platformDefaults.baseUrl).setValue(platformConfig.baseUrl || "").onChange(async (value) => {
        this.plugin.settings.platforms[currentPlatform].baseUrl = value || platformDefaults.baseUrl;
        await this.plugin.saveSettings();
      });
    });
    new import_obsidian3.Setting(containerEl).setName("Temperature").setDesc("\u751F\u6210\u968F\u673A\u6027\uFF080-2\uFF0C\u8D8A\u4F4E\u8D8A\u786E\u5B9A\uFF09").addSlider(
      (slider) => {
        var _a;
        return slider.setLimits(0, 2, 0.1).setValue((_a = platformConfig.temperature) != null ? _a : 0.7).setDynamicTooltip().onChange(async (value) => {
          this.plugin.settings.platforms[currentPlatform].temperature = value;
          await this.plugin.saveSettings();
        });
      }
    );
    new import_obsidian3.Setting(containerEl).setName("Max tokens").setDesc("\u6700\u5927\u751F\u6210\u4EE4\u724C\u6570").addSlider(
      (slider) => slider.setLimits(512, 8192, 512).setValue(platformConfig.maxTokens || 4096).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.platforms[currentPlatform].maxTokens = value;
        await this.plugin.saveSettings();
      })
    );
  }
  displayFeatureSettings(containerEl) {
    new import_obsidian3.Setting(containerEl).setName("\u7B14\u8BB0\u5C5E\u6027\u8BBE\u7F6E").setHeading();
    new import_obsidian3.Setting(containerEl).setName("\u6700\u5927\u6807\u7B7E\u6570").setDesc("\u751F\u6210\u65F6\u53C2\u8003\u7684\u5DF2\u6709\u6807\u7B7E\u6700\u5927\u6570\u91CF").addSlider(
      (slider) => slider.setLimits(1, 10, 1).setValue(this.plugin.settings.maxTags).setDynamicTooltip().onChange(async (value) => {
        this.plugin.settings.maxTags = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u5305\u542B\u6587\u4EF6\u5939\u7ED3\u6784").setDesc("\u5C06\u6587\u4EF6\u6240\u5728\u6587\u4EF6\u5939\u4F5C\u4E3A\u5206\u7C7B\u5EFA\u8BAE").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.includeFolderStructure).onChange(async (value) => {
        this.plugin.settings.includeFolderStructure = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u751F\u6210\u524D\u663E\u793A\u9884\u89C8").setDesc("\u5F00\u542F\u540E\uFF0C\u751F\u6210\u7B14\u8BB0\u5C5E\u6027\u65F6\u4F1A\u5148\u663E\u793A\u9884\u89C8\u7A97\u53E3\uFF1B\u5173\u95ED\u9009\u9879\u5219\u76F4\u63A5\u5E94\u7528").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showPreview).onChange(async (value) => {
        this.plugin.settings.showPreview = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u663E\u793A\u53F3\u952E\u83DC\u5355").setDesc("\u5728\u6587\u4EF6\u6D4F\u89C8\u5668\u548C\u7F16\u8F91\u5668\u53F3\u952E\u83DC\u5355\u4E2D\u663E\u793A AI \u751F\u6210\u7B14\u8BB0\u5C5E\u6027\u9009\u9879").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showEditorMenu).onChange(async (value) => {
        this.plugin.settings.showEditorMenu = value;
        await this.plugin.saveSettings();
        this.plugin.updateContextMenus();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u6587\u672C\u4F18\u5316\u8BBE\u7F6E").setHeading();
    new import_obsidian3.Setting(containerEl).setName("\u4F18\u5316\u524D\u663E\u793A\u9884\u89C8").setDesc("\u5F00\u542F\u540E\uFF0C\u4F18\u5316\u6587\u672C\u524D\u4F1A\u5148\u663E\u793A\u9884\u89C8\u7A97\u53E3\uFF1B\u5173\u95ED\u9009\u9879\u5219\u76F4\u63A5\u5E94\u7528").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showOptimizePreview).onChange(async (value) => {
        this.plugin.settings.showOptimizePreview = value;
        await this.plugin.saveSettings();
      })
    );
    new import_obsidian3.Setting(containerEl).setName("\u663E\u793A\u4F18\u5316\u83DC\u5355").setDesc("\u5728\u6587\u4EF6\u6D4F\u89C8\u5668\u548C\u7F16\u8F91\u5668\u53F3\u952E\u83DC\u5355\u4E2D\u663E\u793A AI \u4F18\u5316\u6587\u672C\u9009\u9879").addToggle(
      (toggle) => toggle.setValue(this.plugin.settings.showOptimizeMenu).onChange(async (value) => {
        this.plugin.settings.showOptimizeMenu = value;
        await this.plugin.saveSettings();
        if (value) {
          this.plugin.addOptimizeContextMenus();
        } else {
          this.plugin.removeOptimizeContextMenus();
        }
      })
    );
  }
  /**
   * 为本地平台（Ollama / LM Studio）构建自动拉取模型的下拉框
   */
  buildLocalModelDropdown(modelSetting, platformConfig, platform) {
    const currentPlatform = this.plugin.settings.activePlatform;
    const platformDefaults = PLATFORM_DEFAULTS[currentPlatform];
    const baseUrl = platformConfig.baseUrl || platformDefaults.baseUrl;
    const fetchFn = getFetchFunction(platform);
    let dropdown;
    modelSetting.addDropdown((dd) => {
      dropdown = dd;
      dropdown.addOption("__loading__", "\u6B63\u5728\u83B7\u53D6\u672C\u5730\u6A21\u578B\u5217\u8868...");
      dropdown.setValue("__loading__");
      dropdown.onChange(async (value) => {
        if (value && value !== "__loading__") {
          this.plugin.settings.platforms[currentPlatform].model = value;
          await this.plugin.saveSettings();
        }
      });
    });
    void this.populateLocalModels(dropdown, fetchFn, baseUrl);
  }
  async populateLocalModels(dropdown, fetchFn, baseUrl) {
    const currentPlatform = this.plugin.settings.activePlatform;
    const savedModel = this.plugin.settings.platforms[currentPlatform].model;
    const models = await fetchFn(baseUrl);
    const selectEl = dropdown.selectEl;
    selectEl.innerHTML = "";
    if (models.length === 0) {
      dropdown.addOption("", "\u672A\u80FD\u83B7\u53D6\u6A21\u578B\u5217\u8868\uFF0C\u8BF7\u68C0\u67E5\u670D\u52A1\u662F\u5426\u8FD0\u884C");
      dropdown.setValue("");
      return;
    }
    for (const model of models) {
      dropdown.addOption(model, model);
    }
    if (models.includes(savedModel)) {
      dropdown.setValue(savedModel);
    } else {
      dropdown.setValue(models[0]);
      this.plugin.settings.platforms[currentPlatform].model = models[0];
    }
  }
};

// src/modals/metadata-preview-modal.ts
var import_obsidian4 = require("obsidian");
var MetadataPreviewModal = class extends import_obsidian4.Modal {
  constructor(app, result, onConfirm) {
    super(app);
    this.onConfirm = () => {
    };
    this.result = result;
    this.onConfirm = onConfirm;
    this.editedResult = {
      title: result.title || "",
      tags: Array.isArray(result.tags) ? [...result.tags] : [],
      category: result.category || "",
      summary: result.summary || "",
      keywords: Array.isArray(result.keywords) ? [...result.keywords] : [],
      share: result.share || false
    };
  }
  onOpen() {
    var _a;
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "AI \u751F\u6210\u7684\u7B14\u8BB0\u5C5E\u6027" });
    const titleContainer = contentEl.createDiv();
    titleContainer.createEl("label", { text: "\u6807\u9898:" });
    const titleInput = titleContainer.createEl("input", {
      type: "text",
      value: this.editedResult.title,
      cls: "ai-metadata-input ai-metadata-input-full"
    });
    titleInput.addEventListener("input", (e) => {
      this.editedResult.title = e.target.value;
    });
    const tagsContainer = contentEl.createDiv({ cls: "ai-metadata-tags" });
    tagsContainer.createEl("label", { text: "\u6807\u7B7E:" });
    const tagsInput = tagsContainer.createEl("input", {
      type: "text",
      value: this.editedResult.tags.join(", "),
      cls: "ai-metadata-input ai-metadata-input-full"
    });
    tagsInput.addEventListener("input", (e) => {
      const value = e.target.value;
      this.editedResult.tags = value.split(",").map((t) => t.trim()).filter((t) => t.length > 0);
    });
    const categoryContainer = contentEl.createDiv();
    categoryContainer.createEl("label", { text: "\u5206\u7C7B:" });
    const categoryInput = categoryContainer.createEl("input", {
      type: "text",
      value: this.editedResult.category,
      cls: "ai-metadata-input ai-metadata-input-full"
    });
    categoryInput.addEventListener("input", (e) => {
      this.editedResult.category = e.target.value;
    });
    const summaryContainer = contentEl.createDiv();
    summaryContainer.createEl("label", { text: "\u6458\u8981:" });
    const summaryInput = summaryContainer.createEl("textarea", {
      cls: "ai-metadata-textarea ai-metadata-textarea-full"
    });
    summaryInput.value = this.editedResult.summary;
    summaryInput.addEventListener("input", (e) => {
      this.editedResult.summary = e.target.value;
    });
    const keywordsContainer = contentEl.createDiv();
    keywordsContainer.createEl("label", { text: "\u5173\u952E\u8BCD:" });
    const keywordsInput = keywordsContainer.createEl("input", {
      type: "text",
      value: ((_a = this.editedResult.keywords) == null ? void 0 : _a.join(", ")) || "",
      cls: "ai-metadata-input ai-metadata-input-full"
    });
    keywordsInput.addEventListener("input", (e) => {
      const value = e.target.value;
      this.editedResult.keywords = value.split(",").map((t) => t.trim()).filter((t) => t.length > 0);
    });
    const shareContainer = contentEl.createDiv({ cls: "ai-metadata-share ai-metadata-share-container" });
    shareContainer.createEl("label", { text: "\u5141\u8BB8\u5206\u4EAB: ", cls: "ai-metadata-share-label" });
    const shareCheckbox = shareContainer.createEl("input", {
      type: "checkbox"
    });
    shareCheckbox.checked = this.editedResult.share === true;
    shareCheckbox.addEventListener("change", (e) => {
      this.editedResult.share = e.target.checked;
    });
    shareContainer.createEl("span", { text: " (\u9009\u62E9\u662F\u5219\u8FFD\u52A0 share: true)" });
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const confirmButton = buttonContainer.createEl("button", {
      text: "\u5E94\u7528",
      cls: "mod-cta"
    });
    confirmButton.addEventListener("click", () => {
      if (typeof this.onConfirm === "function") {
        this.onConfirm(true, this.editedResult);
      }
      this.close();
    });
    const cancelButton = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88"
    });
    cancelButton.addEventListener("click", () => {
      if (typeof this.onConfirm === "function") {
        this.onConfirm(false);
      }
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// src/modals/text-optimization-modal.ts
var import_obsidian5 = require("obsidian");
var TextOptimizationModal = class extends import_obsidian5.Modal {
  constructor(app, result, isPartial, onConfirm) {
    super(app);
    this.onConfirm = () => {
    };
    this.currentMode = "source";
    this.result = result;
    this.isPartial = isPartial;
    this.onConfirm = onConfirm;
    this.editedText = result.optimizedText || "";
    this.component = new import_obsidian5.Component();
    this.component.load();
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    this.modalEl.classList.add("ai-optimize-modal");
    contentEl.createEl("h2", { text: this.isPartial ? "AI \u6587\u672C\u4F18\u5316\uFF08\u9009\u4E2D\u7247\u6BB5\uFF09" : "AI \u6587\u672C\u4F18\u5316\uFF08\u5168\u6587\uFF09" });
    const mainContainer = contentEl.createDiv({ cls: "ai-optimize-container" });
    const leftPanel = mainContainer.createDiv({ cls: "ai-optimize-left" });
    const tabHeader = leftPanel.createDiv({ cls: "ai-optimize-tab-header" });
    this.sourceTabBtn = tabHeader.createEl("button", {
      text: "\u6E90\u7801\u6A21\u5F0F",
      cls: "ai-optimize-tab ai-optimize-tab-active"
    });
    this.previewTabBtn = tabHeader.createEl("button", {
      text: "\u9605\u8BFB\u89C6\u56FE",
      cls: "ai-optimize-tab"
    });
    this.sourceTabBtn.addEventListener("click", () => void this.switchMode("source"));
    this.previewTabBtn.addEventListener("click", () => void this.switchMode("preview"));
    const refreshBtn = tabHeader.createEl("button", {
      text: "\u5237\u65B0",
      cls: "ai-optimize-refresh-btn"
    });
    refreshBtn.addEventListener("click", () => void this.refreshPreview());
    this.refreshBtn = refreshBtn;
    const editorContainer = leftPanel.createDiv({ cls: "ai-optimize-editor" });
    this.editorEl = editorContainer.createEl("div", { cls: "ai-optimize-editable" });
    this.editorEl.contentEditable = "true";
    this.editorEl.textContent = this.editedText;
    this.previewEl = editorContainer.createEl("div", {
      cls: "ai-optimize-preview markdown-rendered markdown-preview-view"
    });
    this.editorEl.addEventListener("input", () => {
      this.editedText = this.editorEl.textContent || "";
    });
    const rightPanel = mainContainer.createDiv({ cls: "ai-optimize-right" });
    const suggestionContainer = rightPanel.createDiv({ cls: "ai-optimize-suggestions" });
    if (this.result.explanation) {
      const suggestions = this.parseSuggestions(this.result.explanation);
      if (suggestions.length > 0) {
        suggestions.forEach((suggestion) => {
          const itemDiv = suggestionContainer.createEl("div", { cls: "ai-optimize-suggestion-item" });
          itemDiv.createEl("span", { text: "\u2022 ", cls: "ai-optimize-suggestion-bullet" });
          itemDiv.createEl("span", { text: suggestion, cls: "ai-optimize-suggestion-text" });
        });
      } else {
        suggestionContainer.createEl("div", {
          text: this.result.explanation,
          cls: "ai-optimize-suggestion-text"
        });
      }
    } else {
      suggestionContainer.createEl("div", {
        text: "\u65E0\u4F18\u5316\u5EFA\u8BAE",
        cls: "ai-optimize-no-suggestions"
      });
    }
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const confirmButton = buttonContainer.createEl("button", {
      text: "\u5E94\u7528",
      cls: "mod-cta"
    });
    confirmButton.addEventListener("click", () => {
      if (typeof this.onConfirm === "function") {
        this.onConfirm(true, this.editedText);
      }
      this.close();
    });
    const cancelButton = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88"
    });
    cancelButton.addEventListener("click", () => {
      if (typeof this.onConfirm === "function") {
        this.onConfirm(false);
      }
      this.close();
    });
  }
  /**
   * 切换编辑器模式
   */
  async switchMode(mode) {
    if (this.currentMode === mode)
      return;
    this.currentMode = mode;
    if (mode === "source") {
      this.editorEl.classList.remove("hidden");
      this.previewEl.classList.remove("visible");
      this.sourceTabBtn.classList.add("ai-optimize-tab-active");
      this.previewTabBtn.classList.remove("ai-optimize-tab-active");
      this.refreshBtn.classList.remove("visible");
    } else {
      this.editorEl.classList.add("hidden");
      this.previewEl.classList.add("visible");
      this.previewTabBtn.classList.add("ai-optimize-tab-active");
      this.sourceTabBtn.classList.remove("ai-optimize-tab-active");
      this.refreshBtn.classList.add("visible");
      await this.refreshPreview();
    }
  }
  /**
   * 刷新预览内容
   */
  async refreshPreview() {
    this.editedText = this.editorEl.textContent || "";
    this.previewEl.empty();
    await import_obsidian5.MarkdownRenderer.render(
      this.app,
      this.editedText,
      this.previewEl,
      "",
      this.component
    );
  }
  /**
   * 解析优化建议，按条目分割
   */
  parseSuggestions(explanation) {
    if (!explanation)
      return [];
    let suggestions = explanation.split(/\d+[.、]\s*/).filter((s) => s.trim());
    if (suggestions.length <= 1) {
      suggestions = explanation.split(/\n+/).filter((s) => s.trim());
    }
    if (suggestions.length <= 1) {
      suggestions = explanation.split(/[;；]/).filter((s) => s.trim());
    }
    return suggestions.map((s) => s.trim()).filter((s) => s.length > 0);
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
    this.component.unload();
  }
};

// src/modals/batch-confirm-modal.ts
var import_obsidian6 = require("obsidian");
var BatchConfirmModal = class extends import_obsidian6.Modal {
  constructor(app, fileCount, onConfirm) {
    super(app);
    this.fileCount = fileCount;
    this.onConfirm = onConfirm;
  }
  onOpen() {
    const { contentEl } = this;
    contentEl.empty();
    contentEl.createEl("h2", { text: "\u786E\u8BA4\u6279\u91CF\u751F\u6210" });
    contentEl.createEl("p", { text: `\u5C06\u4E3A ${this.fileCount} \u4E2A\u6587\u4EF6\u751F\u6210 AI \u7B14\u8BB0\u5C5E\u6027\u3002` });
    contentEl.createEl("p", { text: "\u6B64\u64CD\u4F5C\u53EF\u80FD\u9700\u8981\u4E00\u4E9B\u65F6\u95F4\uFF0C\u8BF7\u8010\u5FC3\u7B49\u5F85\u3002", cls: "mod-warning" });
    const buttonContainer = contentEl.createDiv({ cls: "modal-button-container" });
    const confirmButton = buttonContainer.createEl("button", {
      text: "\u5F00\u59CB",
      cls: "mod-cta"
    });
    confirmButton.addEventListener("click", () => {
      this.onConfirm(true);
      this.close();
    });
    const cancelButton = buttonContainer.createEl("button", {
      text: "\u53D6\u6D88"
    });
    cancelButton.addEventListener("click", () => {
      this.onConfirm(false);
      this.close();
    });
  }
  onClose() {
    const { contentEl } = this;
    contentEl.empty();
  }
};

// main.ts
var AIMetadataPlugin = class extends import_obsidian7.Plugin {
  constructor() {
    super(...arguments);
    this.statusBarItem = null;
    this.ribbonIconEl = null;
    this.showFileMenu = false;
    this.showFolderMenu = false;
    this.showEditorContextMenu = false;
    this.showOptimizeContextMenu = false;
    this.statusBarTimeout = null;
  }
  async onload() {
    await this.loadSettings();
    this.vaultScanner = new VaultScanner(
      this.app.vault,
      () => {
        const cache = this.app.metadataCache;
        return cache.getTags();
      },
      (file) => this.app.metadataCache.getFileCache(file),
      () => {
        const cache = this.app.metadataCache;
        return cache.getCachedFiles();
      }
    );
    this.statusBarItem = this.addStatusBarItem();
    if (this.settings.showEditorMenu) {
      this.addContextMenus();
    }
    if (this.settings.showOptimizeMenu) {
      this.addOptimizeContextMenus();
    }
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (this.showFileMenu && file instanceof import_obsidian7.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("AI \u751F\u6210\u7B14\u8BB0\u5C5E\u6027").setIcon("sparkles").onClick(async () => {
              if (this.settings.showPreview) {
                await this.generateMetadataWithPreview(file);
              } else {
                await this.generateMetadata(file);
              }
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("file-menu", (menu, file) => {
        if (this.showOptimizeContextMenu && file instanceof import_obsidian7.TFile && file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("AI \u4F18\u5316\u6587\u672C").setIcon("wand-2").onClick(async () => {
              const leaf = this.app.workspace.getLeaf(false);
              await leaf.openFile(file);
              const view = this.app.workspace.getActiveViewOfType(import_obsidian7.MarkdownView);
              if (view) {
                await this.optimizeText(view.editor, file);
              }
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        if (this.showEditorContextMenu && view.file && view.file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("AI \u751F\u6210\u7B14\u8BB0\u5C5E\u6027").setIcon("sparkles").onClick(async () => {
              if (this.settings.showPreview) {
                await this.generateMetadataWithPreview(view.file);
              } else {
                await this.generateMetadata(view.file);
              }
            });
          });
        }
      })
    );
    this.registerEvent(
      this.app.workspace.on("editor-menu", (menu, editor, view) => {
        if (this.showOptimizeContextMenu && view.file && view.file.extension === "md") {
          menu.addItem((item) => {
            item.setTitle("AI \u4F18\u5316\u6587\u672C").setIcon("wand-2").onClick(async () => {
              await this.optimizeText(editor, view.file);
            });
          });
        }
      })
    );
    this.addCommand({
      id: "generate-metadata",
      name: "\u7ED9\u5F53\u524D\u6587\u7AE0\u751F\u6210\u7B14\u8BB0\u5C5E\u6027",
      editorCallback: async (editor, view) => {
        await this.generateMetadata(view.file);
      }
    });
    this.addCommand({
      id: "generate-metadata-with-preview",
      name: "\u7ED9\u5F53\u524D\u6587\u7AE0\u751F\u6210\u7B14\u8BB0\u5C5E\u6027\uFF08\u9884\u89C8\uFF09",
      editorCallback: async (editor, view) => {
        await this.generateMetadataWithPreview(view.file);
      }
    });
    this.addCommand({
      id: "optimize-text",
      name: "AI \u4F18\u5316\u6587\u672C",
      editorCallback: async (editor, view) => {
        await this.optimizeText(editor, view.file);
      }
    });
    this.addCommand({
      id: "optimize-text-with-preview",
      name: "AI \u4F18\u5316\u6587\u672C\uFF08\u9884\u89C8\uFF09",
      editorCallback: async (editor, view) => {
        await this.optimizeTextWithPreview(editor, view.file);
      }
    });
    this.addSettingTab(new AIMetadataSettingTab(this.app, this));
  }
  onunload() {
  }
  async loadSettings() {
    const loaded = await this.loadData();
    this.settings = Object.assign({}, DEFAULT_SETTINGS, loaded);
    for (const platform of Object.keys(PLATFORM_DEFAULTS)) {
      if (!this.settings.platforms[platform]) {
        this.settings.platforms[platform] = {
          apiKey: "",
          model: PLATFORM_DEFAULTS[platform].defaultModel,
          baseUrl: PLATFORM_DEFAULTS[platform].baseUrl,
          temperature: 0.7,
          maxTokens: 4096
        };
      }
    }
  }
  async saveSettings() {
    await this.saveData(this.settings);
  }
  addRibbonIconButton() {
    if (this.ribbonIconEl)
      return;
    this.ribbonIconEl = this.addRibbonIcon("sparkles", "AI \u751F\u6210\u7B14\u8BB0\u5C5E\u6027", async () => {
      const activeFile = this.app.workspace.getActiveFile();
      if (activeFile && activeFile.extension === "md") {
        if (this.settings.showPreview) {
          await this.generateMetadataWithPreview(activeFile);
        } else {
          await this.generateMetadata(activeFile);
        }
      } else {
        new import_obsidian7.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A Markdown \u6587\u4EF6");
      }
    });
  }
  removeRibbonIconButton() {
    if (this.ribbonIconEl) {
      this.ribbonIconEl.remove();
      this.ribbonIconEl = null;
    }
  }
  addContextMenus() {
    this.showFileMenu = true;
    this.showEditorContextMenu = true;
  }
  removeContextMenus() {
    this.showFileMenu = false;
    this.showEditorContextMenu = false;
  }
  addOptimizeContextMenus() {
    this.showOptimizeContextMenu = true;
  }
  removeOptimizeContextMenus() {
    this.showOptimizeContextMenu = false;
  }
  updateRibbonIcon() {
    if (this.settings.showRibbonIcon) {
      this.addRibbonIconButton();
    } else {
      this.removeRibbonIconButton();
    }
  }
  updateContextMenus() {
    if (this.settings.showEditorMenu) {
      this.addContextMenus();
    } else {
      this.removeContextMenus();
    }
  }
  updateStatusBar(text, isTransient = true) {
    if (!this.statusBarItem)
      return;
    if (this.statusBarTimeout) {
      window.clearTimeout(this.statusBarTimeout);
      this.statusBarTimeout = null;
    }
    this.statusBarItem.setText(`\u{1F916} ${text}`);
    if (isTransient) {
      this.statusBarTimeout = window.setTimeout(() => {
        if (this.statusBarItem) {
          this.statusBarItem.setText("");
        }
      }, 3e3);
    }
  }
  getCurrentPlatformConfig() {
    const platform = this.settings.activePlatform;
    return this.settings.platforms[platform];
  }
  getAIProvider() {
    const platform = this.settings.activePlatform;
    const config = this.getCurrentPlatformConfig();
    if (!config.apiKey) {
      throw new Error(`\u8BF7\u5148\u5728\u8BBE\u7F6E\u4E2D\u914D\u7F6E ${PLATFORM_DEFAULTS[platform].name} \u7684 API Key`);
    }
    return createAIProvider(platform, config);
  }
  async generateMetadata(file) {
    var _a;
    if (!file) {
      new import_obsidian7.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u4EF6");
      return;
    }
    this.updateStatusBar("\u751F\u6210\u4E2D...", false);
    new import_obsidian7.Notice(`\u6B63\u5728\u4F7F\u7528 ${PLATFORM_DEFAULTS[this.settings.activePlatform].name} \u751F\u6210\u7B14\u8BB0\u5C5E\u6027...`);
    try {
      const content = await this.app.vault.read(file);
      const cleanContent = this.extractContentWithoutFrontmatter(content);
      const vaultMetadata = this.vaultScanner.getVaultMetadata(this.settings.includeFolderStructure);
      const existingTags = this.vaultScanner.getTopTags(vaultMetadata.tags, this.settings.maxTags);
      const existingCategories = this.vaultScanner.getTopCategories(vaultMetadata.categories, 20);
      if (this.settings.includeFolderStructure) {
        const folderCategories = this.vaultScanner.getFolderCategories(file);
        for (const cat of folderCategories) {
          if (!existingCategories.includes(cat)) {
            existingCategories.push(cat);
          }
        }
      }
      const provider = this.getAIProvider();
      const result = await provider.analyze(cleanContent, existingTags, existingCategories);
      const existingFrontmatter = this.extractFrontmatter(content);
      if (existingFrontmatter.share === true || existingFrontmatter.share === "true") {
        result.share = true;
      }
      await this.applyMetadata(file, content, result);
      this.updateStatusBar("\u751F\u6210\u5B8C\u6210");
      new import_obsidian7.Notice(`\u7B14\u8BB0\u5C5E\u6027\u751F\u6210\u5B8C\u6210\uFF01
\u6807\u9898: ${result.title}
\u6807\u7B7E: ${result.tags.join(", ")}
\u5173\u952E\u8BCD: ${((_a = result.keywords) == null ? void 0 : _a.join(", ")) || "\u65E0"}`);
    } catch (error) {
      console.error("\u751F\u6210\u5931\u8D25:", error);
      this.updateStatusBar("\u751F\u6210\u5931\u8D25");
      new import_obsidian7.Notice(`\u751F\u6210\u5931\u8D25: ${error.message}`);
    }
  }
  async generateMetadataWithPreview(file) {
    if (!file) {
      new import_obsidian7.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u4EF6");
      return;
    }
    this.updateStatusBar("\u751F\u6210\u4E2D...", false);
    new import_obsidian7.Notice(`\u6B63\u5728\u4F7F\u7528 ${PLATFORM_DEFAULTS[this.settings.activePlatform].name} \u751F\u6210\u7B14\u8BB0\u5C5E\u6027...`);
    try {
      const content = await this.app.vault.read(file);
      const cleanContent = this.extractContentWithoutFrontmatter(content);
      const vaultMetadata = this.vaultScanner.getVaultMetadata(this.settings.includeFolderStructure);
      const existingTags = this.vaultScanner.getTopTags(vaultMetadata.tags, this.settings.maxTags);
      const existingCategories = this.vaultScanner.getTopCategories(vaultMetadata.categories, 20);
      if (this.settings.includeFolderStructure) {
        const folderCategories = this.vaultScanner.getFolderCategories(file);
        for (const cat of folderCategories) {
          if (!existingCategories.includes(cat)) {
            existingCategories.push(cat);
          }
        }
      }
      const provider = this.getAIProvider();
      const result = await provider.analyze(cleanContent, existingTags, existingCategories);
      const existingFrontmatter = this.extractFrontmatter(content);
      if (existingFrontmatter.share === true || existingFrontmatter.share === "true") {
        result.share = true;
      }
      this.updateStatusBar("\u9884\u89C8\u4E2D", false);
      new MetadataPreviewModal(this.app, result, (confirmed, editedResult) => {
        if (confirmed && editedResult) {
          this.applyMetadata(file, content, editedResult).then(() => {
            var _a;
            this.updateStatusBar("\u5DF2\u5E94\u7528");
            new import_obsidian7.Notice(`\u7B14\u8BB0\u5C5E\u6027\u5DF2\u5E94\u7528\uFF01
\u6807\u9898: ${editedResult.title}
\u6807\u7B7E: ${editedResult.tags.join(", ")}
\u5173\u952E\u8BCD: ${((_a = editedResult.keywords) == null ? void 0 : _a.join(", ")) || "\u65E0"}`);
          }).catch((error) => {
            console.error("\u5E94\u7528\u7B14\u8BB0\u5C5E\u6027\u5931\u8D25:", error);
            this.updateStatusBar("\u5E94\u7528\u5931\u8D25");
            new import_obsidian7.Notice(`\u5E94\u7528\u5931\u8D25: ${error.message}`);
          });
        } else {
          this.updateStatusBar("\u5DF2\u53D6\u6D88");
        }
      }).open();
    } catch (error) {
      console.error("\u751F\u6210\u5931\u8D25:", error);
      this.updateStatusBar("\u751F\u6210\u5931\u8D25");
      new import_obsidian7.Notice(`\u751F\u6210\u5931\u8D25: ${error.message}`);
    }
  }
  updateMetadata(file) {
    if (!file) {
      new import_obsidian7.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u4EF6");
      return;
    }
    this.updateStatusBar("\u66F4\u65B0\u4E2D...", false);
    try {
      const fileTags = this.vaultScanner.getFileTags(file);
      const fileCategory = this.vaultScanner.getFileCategory(file);
      this.updateStatusBar("\u66F4\u65B0\u5B8C\u6210");
      new import_obsidian7.Notice(`\u6587\u4EF6\u6807\u7B7E: ${fileTags.join(", ") || "\u65E0"}, \u5206\u7C7B: ${fileCategory || "\u65E0"}`);
    } catch (error) {
      console.error("\u66F4\u65B0\u5931\u8D25:", error);
      this.updateStatusBar("\u66F4\u65B0\u5931\u8D25");
      new import_obsidian7.Notice("\u66F4\u65B0\u5931\u8D25");
    }
  }
  async applyMetadata(file, originalContent, result) {
    const safeResult = {
      title: (result == null ? void 0 : result.title) || "",
      tags: Array.isArray(result == null ? void 0 : result.tags) ? result.tags : [],
      category: (result == null ? void 0 : result.category) || "",
      summary: (result == null ? void 0 : result.summary) || "",
      keywords: Array.isArray(result == null ? void 0 : result.keywords) ? result.keywords : [],
      share: (result == null ? void 0 : result.share) === true
    };
    const existingFrontmatter = this.extractFrontmatter(originalContent);
    let dateStr = existingFrontmatter == null ? void 0 : existingFrontmatter.date;
    if (!dateStr) {
      const stat = await this.app.vault.adapter.stat(file.path);
      if (stat) {
        const date = new Date(stat.ctime);
        const year = date.getFullYear();
        const month = String(date.getMonth() + 1).padStart(2, "0");
        const day = String(date.getDate()).padStart(2, "0");
        const hours = String(date.getHours()).padStart(2, "0");
        const minutes = String(date.getMinutes()).padStart(2, "0");
        const seconds = String(date.getSeconds()).padStart(2, "0");
        dateStr = `${year}-${month}-${day} ${hours}:${minutes}:${seconds}`;
      }
    }
    safeResult.date = typeof dateStr === "string" ? dateStr : void 0;
    const newFrontmatter = this.buildFrontmatter(safeResult);
    const cleanContent = this.extractContentWithoutFrontmatter(originalContent);
    const newContent = `${newFrontmatter}
${cleanContent}`;
    await this.app.vault.modify(file, newContent);
  }
  posToOffset(content, pos) {
    const lines = content.split("\n");
    let offset = 0;
    for (let i = 0; i < pos.line && i < lines.length; i++) {
      offset += lines[i].length + 1;
    }
    return Math.min(offset + pos.ch, content.length);
  }
  async applyOptimizedText(file, editor, isPartial, originalSelection, selectionFrom, selectionTo, optimizedText) {
    const currentValue = editor.getValue();
    let newValue = currentValue;
    if (isPartial) {
      if (!selectionFrom || !selectionTo) {
        throw new Error("\u65E0\u6CD5\u83B7\u53D6\u9009\u4E2D\u8303\u56F4");
      }
      const fromOffset = this.posToOffset(currentValue, selectionFrom);
      const toOffset = this.posToOffset(currentValue, selectionTo);
      const start = Math.min(fromOffset, toOffset);
      const end = Math.max(fromOffset, toOffset);
      const currentSelectedText = currentValue.slice(start, end);
      if (currentSelectedText === originalSelection) {
        newValue = currentValue.slice(0, start) + optimizedText + currentValue.slice(end);
      } else {
        const nearStart = Math.max(0, start - 200);
        let idx = currentValue.indexOf(originalSelection, nearStart);
        if (idx === -1)
          idx = currentValue.indexOf(originalSelection);
        if (idx === -1) {
          throw new Error("\u65E0\u6CD5\u5728\u6587\u6863\u4E2D\u5B9A\u4F4D\u539F\u9009\u4E2D\u6587\u672C\uFF08\u53EF\u80FD\u5DF2\u88AB\u4FEE\u6539\uFF09");
        }
        newValue = currentValue.slice(0, idx) + optimizedText + currentValue.slice(idx + originalSelection.length);
      }
    } else {
      newValue = optimizedText;
    }
    await this.app.vault.modify(file, newValue);
    editor.setValue(newValue);
  }
  buildFrontmatter(result) {
    const title = (result == null ? void 0 : result.title) || "";
    const tags = Array.isArray(result == null ? void 0 : result.tags) ? result.tags : [];
    const category = (result == null ? void 0 : result.category) || "";
    const summary = (result == null ? void 0 : result.summary) || "";
    const date = (result == null ? void 0 : result.date) || "";
    const keywords = Array.isArray(result == null ? void 0 : result.keywords) ? result.keywords : [];
    const lines = ["---"];
    if (date) {
      lines.push(`date: ${date}`);
    }
    if (title) {
      lines.push(`title: ${title}`);
    }
    if (tags.length > 0) {
      lines.push(`tags:`);
      for (const tag of tags) {
        lines.push(`  - ${tag}`);
      }
    }
    if (category) {
      lines.push(`category: ${category}`);
    }
    if (keywords.length > 0) {
      lines.push(`keywords:`);
      for (const kw of keywords) {
        lines.push(`  - ${kw}`);
      }
    }
    if (summary) {
      lines.push(`summary: ${summary}`);
    }
    if ((result == null ? void 0 : result.share) === true) {
      lines.push(`share: true`);
    }
    lines.push("---");
    return lines.join("\n");
  }
  extractContentWithoutFrontmatter(content) {
    const match = content.match(/^---\s*\n[\s\S]*?\n---\s*/);
    if (match) {
      return content.slice(match[0].length).trim();
    }
    return content.trim();
  }
  extractFrontmatter(content) {
    const match = content.match(/^---\s*\n([\s\S]*?)\n---/);
    if (!match)
      return {};
    const yaml = match[1];
    const result = {};
    const lines = yaml.split("\n");
    let currentKey = "";
    let inArray = false;
    for (const line of lines) {
      const trimmed = line.trim();
      const colonIndex = line.indexOf(":");
      if (colonIndex > 0 && !inArray) {
        currentKey = line.slice(0, colonIndex).trim();
        const value = line.slice(colonIndex + 1).trim();
        if (value === "") {
          inArray = true;
          result[currentKey] = [];
        } else if (value.startsWith("[") && value.endsWith("]")) {
          result[currentKey] = value.slice(1, -1).split(",").map((v) => v.trim().replace(/^["']|["']$/g, ""));
        } else {
          result[currentKey] = value.replace(/^["']|["']$/g, "");
        }
      } else if (trimmed.startsWith("-") && inArray && currentKey) {
        const value = trimmed.slice(1).trim();
        const arr = result[currentKey];
        arr.push(value.replace(/^["']|["']$/g, ""));
      } else if (trimmed === "" || colonIndex > 0) {
        inArray = false;
      }
    }
    return result;
  }
  normalizeTags(tags) {
    if (Array.isArray(tags)) {
      return tags.map((t) => String(t).trim()).filter((t) => t.length > 0);
    }
    if (typeof tags === "string") {
      return tags.split(/[,\s]+/).map((t) => t.trim()).filter((t) => t.length > 0);
    }
    return [];
  }
  batchGenerateMetadata(folder) {
    const files = [];
    const collectFiles = (f) => {
      for (const child of f.children) {
        if (child instanceof import_obsidian7.TFile && child.extension === "md") {
          files.push(child);
        } else if (child instanceof import_obsidian7.TFolder) {
          collectFiles(child);
        }
      }
    };
    collectFiles(folder);
    if (files.length === 0) {
      new import_obsidian7.Notice("\u8BE5\u6587\u4EF6\u5939\u4E2D\u6CA1\u6709 Markdown \u6587\u4EF6");
      return;
    }
    new BatchConfirmModal(this.app, files.length, (confirmed) => {
      if (!confirmed)
        return;
      let successCount = 0;
      let failCount = 0;
      this.updateStatusBar(`\u6279\u91CF\u5904\u7406\u4E2D: 0/${files.length}`, false);
      const processFiles = async () => {
        for (let i = 0; i < files.length; i++) {
          const file = files[i];
          try {
            await this.generateMetadata(file);
            successCount++;
          } catch (error) {
            console.error(`\u5904\u7406\u6587\u4EF6 ${file.path} \u5931\u8D25:`, error);
            failCount++;
          }
          this.updateStatusBar(`\u6279\u91CF\u5904\u7406\u4E2D: ${i + 1}/${files.length}`, false);
        }
        this.updateStatusBar("\u6279\u91CF\u5904\u7406\u5B8C\u6210");
        new import_obsidian7.Notice(`\u6279\u91CF\u5904\u7406\u5B8C\u6210\uFF01\u6210\u529F: ${successCount}, \u5931\u8D25: ${failCount}`);
      };
      void processFiles();
    }).open();
  }
  async optimizeText(editor, file) {
    if (!file) {
      new import_obsidian7.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u4EF6");
      return;
    }
    const selection = editor.getSelection();
    const isPartial = selection.length > 0;
    const selectionFrom = isPartial ? editor.getCursor("from") : null;
    const selectionTo = isPartial ? editor.getCursor("to") : null;
    const contentToOptimize = isPartial ? selection : editor.getValue();
    if (!contentToOptimize.trim()) {
      new import_obsidian7.Notice("\u6CA1\u6709\u53EF\u4F18\u5316\u7684\u5185\u5BB9");
      return;
    }
    this.updateStatusBar("\u4F18\u5316\u4E2D...", false);
    new import_obsidian7.Notice(`\u6B63\u5728\u4F7F\u7528 ${PLATFORM_DEFAULTS[this.settings.activePlatform].name} \u4F18\u5316\u6587\u672C...`);
    try {
      const provider = this.getAIProvider();
      const result = await provider.optimize(contentToOptimize, isPartial);
      if (this.settings.showOptimizePreview) {
        this.updateStatusBar("\u9884\u89C8\u4E2D", false);
        new TextOptimizationModal(this.app, result, isPartial, (confirmed, editedText) => {
          if (confirmed && editedText) {
            this.applyOptimizedText(file, editor, isPartial, selection, selectionFrom, selectionTo, editedText).then(() => {
              this.updateStatusBar("\u5DF2\u5E94\u7528");
              new import_obsidian7.Notice("\u6587\u672C\u4F18\u5316\u5DF2\u5E94\u7528\uFF01");
            }).catch((error) => {
              console.error("\u5199\u5165\u5931\u8D25:", error);
              this.updateStatusBar("\u5199\u5165\u5931\u8D25");
              new import_obsidian7.Notice(`\u5199\u5165\u5931\u8D25: ${error.message}`);
            });
          } else {
            this.updateStatusBar("\u5DF2\u53D6\u6D88");
          }
        }).open();
      } else {
        await this.applyOptimizedText(file, editor, isPartial, selection, selectionFrom, selectionTo, result.optimizedText);
        this.updateStatusBar("\u5DF2\u5E94\u7528");
        new import_obsidian7.Notice("\u6587\u672C\u4F18\u5316\u5DF2\u5E94\u7528\uFF01");
      }
    } catch (error) {
      console.error("\u4F18\u5316\u5931\u8D25:", error);
      this.updateStatusBar("\u4F18\u5316\u5931\u8D25");
      new import_obsidian7.Notice(`\u4F18\u5316\u5931\u8D25: ${error.message}`);
    }
  }
  async optimizeTextWithPreview(editor, file) {
    if (!file) {
      new import_obsidian7.Notice("\u8BF7\u5148\u6253\u5F00\u4E00\u4E2A\u6587\u4EF6");
      return;
    }
    const selection = editor.getSelection();
    const isPartial = selection.length > 0;
    const selectionFrom = isPartial ? editor.getCursor("from") : null;
    const selectionTo = isPartial ? editor.getCursor("to") : null;
    const contentToOptimize = isPartial ? selection : editor.getValue();
    if (!contentToOptimize.trim()) {
      new import_obsidian7.Notice("\u6CA1\u6709\u53EF\u4F18\u5316\u7684\u5185\u5BB9");
      return;
    }
    this.updateStatusBar("\u4F18\u5316\u4E2D...", false);
    new import_obsidian7.Notice(`\u6B63\u5728\u4F7F\u7528 ${PLATFORM_DEFAULTS[this.settings.activePlatform].name} \u4F18\u5316\u6587\u672C...`);
    try {
      const provider = this.getAIProvider();
      const result = await provider.optimize(contentToOptimize, isPartial);
      this.updateStatusBar("\u9884\u89C8\u4E2D", false);
      new TextOptimizationModal(this.app, result, isPartial, (confirmed, editedText) => {
        if (confirmed && editedText) {
          this.applyOptimizedText(file, editor, isPartial, selection, selectionFrom, selectionTo, editedText).then(() => {
            this.updateStatusBar("\u5DF2\u5E94\u7528");
            new import_obsidian7.Notice("\u6587\u672C\u4F18\u5316\u5DF2\u5E94\u7528\uFF01");
          }).catch((error) => {
            console.error("\u5199\u5165\u5931\u8D25:", error);
            this.updateStatusBar("\u5199\u5165\u5931\u8D25");
            new import_obsidian7.Notice(`\u5199\u5165\u5931\u8D25: ${error.message}`);
          });
        } else {
          this.updateStatusBar("\u5DF2\u53D6\u6D88");
        }
      }).open();
    } catch (error) {
      console.error("\u4F18\u5316\u5931\u8D25:", error);
      this.updateStatusBar("\u4F18\u5316\u5931\u8D25");
      new import_obsidian7.Notice(`\u4F18\u5316\u5931\u8D25: ${error.message}`);
    }
  }
};
